'use strict';
const originalRun=run;
const stripOriginal=s=>s.normalize('NFD').replace(/[\u0300-\u036f\u0591-\u05c7]/g,'').replace(/ς/g,'σ').toLowerCase();
function resolveBook(name){const n=norm(name).toLowerCase();return books.find(b=>[b.name,b.short,b.code,b.name.replace(/복음$|서$|기$/,'')].some(v=>norm(v).toLowerCase()===n));}
function parsePassage(query){const q=query.trim().replace(/：/g,':');const m=q.match(/^(.+?)\s*(\d+)\s*(?:(?::|장|\s)\s*(\d+)\s*절?(?:\s*[-–~]\s*(\d+)\s*절?)?)?\s*장?\s*$/);if(m){const book=resolveBook(m[1]);if(book)return {book,chapter:+m[2],verse:m[3]?+m[3]:null,end:m[4]?+m[4]:null};}const book=resolveBook(q);return book?{book,chapter:1,verse:null}:null;}
function chapterHTML(book,chapter,data,start,end){const entries=Object.entries(data).filter(([k])=>+k.split(':')[0]===chapter&&(!start||+k.split(':')[1]>=start)&&(!end||+k.split(':')[1]<=end));if(!entries.length)return '<div class="notice">이 판본에 해당 장·절이 없습니다. 아래 책·장·절 선택에서 확인해주세요.</div>';return `<div class="notice chapter-intro"><strong>${esc(book.name)} ${chapter}장${start?' '+start+'–'+end+'절':''}</strong><p>각 구절을 누르면 원문 전체·발음·수록된 의미 풀이를 볼 수 있습니다.</p></div><div class="chapter-list">${entries.map(([key,v])=>`<button class="chapter-verse" data-query="${book.name} ${key}"><span>${key.split(':')[1]}</span><span lang="${book.testament==='ot'?'he':'el'}" dir="${book.testament==='ot'?'rtl':'ltr'}">${esc(v.text)}</span><span>↗</span></button>`).join('')}</div>`;}
async function searchCorpus(q,id){const strong=/^H\d+$/i.test(q)?q.slice(1):null;const needle=stripOriginal(q);const selected=$('corpusScope').value;const targets=books.filter(b=>selected==='all'||b.testament===selected);const found=[];let scanned=0;const pending=[...targets];$('results').innerHTML='<div class="notice" id="corpusProgress" role="status">성경 전체 원문을 검색하고 있습니다…</div>';await Promise.all(Array.from({length:6},async()=>{while(pending.length&&id===requestId){const b=pending.shift();const data=await loadBook(b);if(id!==requestId)return;for(const [key,v] of Object.entries(data)){const hit=strong?v.words?.some(w=>w.s.split('/').some(s=>s.replace(/[a-z\s]/g,'')===strong)):stripOriginal(v.text).includes(needle);if(hit)found.push({b,key,text:v.text});}scanned++;if($('corpusProgress'))$('corpusProgress').textContent=`${targets.length}권 중 ${scanned}권 검색 완료 · ${found.length}개 구절`;}}));if(id!==requestId)return;found.sort((a,b)=>books.indexOf(a.b)-books.indexOf(b.b)||+a.key.split(':')[0]-+b.key.split(':')[0]||+a.key.split(':')[1]-+b.key.split(':')[1]);let page=0;function render(){const pageSize=30,total=Math.max(1,Math.ceil(found.length/pageSize));$('results').innerHTML=`<div class="notice chapter-intro"><strong>${esc(q)} · ${found.length}개 구절</strong><p>${strong?'히브리어 Strong 번호로 형태가 다른 단어의 용례도 검색합니다.':'원문의 문자와 부분 문자열로 검색합니다. 악센트·모음 부호는 구분하지 않으며, 모든 굴절형을 자동으로 묶는 표제어 검색은 아닙니다.'}</p></div><div class="chapter-list">${found.slice(page*pageSize,(page+1)*pageSize).map(r=>`<button class="chapter-verse corpus-hit" data-query="${r.b.name} ${r.key}"><span>${r.b.name}<br>${r.key}</span><span lang="${r.b.testament==='ot'?'he':'el'}" dir="${r.b.testament==='ot'?'rtl':'ltr'}">${esc(r.text)}</span><span>↗</span></button>`).join('')||'<p class="note">일치하는 원문이 없습니다. 다른 형태 또는 Strong 번호로 검색해보세요.</p>'}</div><div class="pagination"><button class="small-btn" id="hitsPrev" ${page===0?'disabled':''}>← 이전</button><span>${page+1} / ${total}</span><button class="small-btn" id="hitsNext" ${page+1===total?'disabled':''}>다음 →</button></div>`;bindQueries();$('hitsPrev').onclick=()=>{page--;render();};$('hitsNext').onclick=()=>{page++;render();};}render();}
run=async function(q,forced){q=q.trim();if(!q)return;const selected=forced||mode;const passage=selected!=='word'?parsePassage(q):null;if(passage?.verse&&!passage.end){await originalRun(`${passage.book.name} ${passage.chapter}:${passage.verse}`,'verse');return;}if(passage){const id=++requestId;$('query').value=q;$('resultHeading').textContent=`${passage.book.name} ${passage.chapter}장 원문`;note('본문을 불러오고 있습니다…');try{const data=await loadBook(passage.book);if(id!==requestId)return;$('results').innerHTML=chapterHTML(passage.book,passage.chapter,data,passage.verse,passage.end);bindQueries();setQueryURL(q);}catch{if(id===requestId)note('본문을 불러오지 못했습니다. 연결을 확인하고 다시 검색해주세요.');}return;}if(/[\u0590-\u05ff\u0370-\u03ff\u1f00-\u1fff]/.test(q)||/^H\d+$/i.test(q)){const id=++requestId;$('query').value=q;$('resultHeading').textContent=`“${q}” 성경 전체 용례`;try{await searchCorpus(q,id);if(id===requestId)setQueryURL(q);}catch{if(id===requestId)note('일부 성경 데이터를 불러오지 못했습니다. 연결을 확인하고 다시 검색해주세요.');}return;}await originalRun(q,forced);if(idleDictionary(q))appendCorpusLinks();};
function idleDictionary(q){return !parsePassage(q)&&document.querySelector('.lex-card');}
function appendCorpusLinks(){document.querySelectorAll('.lex-card').forEach(card=>{if(card.querySelector('[data-corpus-link]'))return;const strong=card.querySelector('.lex-top span:last-child').textContent.replace('STRONG ','');const word=card.querySelector('.lex-word').textContent;const b=document.createElement('button');b.className='small-btn';b.dataset.corpusLink='true';b.textContent='성경 전체 용례 검색 ↗';b.onclick=()=>run(strong.startsWith('H')?strong:word,'auto');card.querySelector('.refs').appendChild(b);});}
function setQueryURL(q){const url=new URL(location.href);url.searchParams.set('q',q);history.replaceState(null,'',url);}
let pickerRequest=0;
async function updatePicker(bookCode,chapter){const id=++pickerRequest;const b=books.find(b=>b.code===bookCode);if(!b)return;const chapterSelect=$('chapterSelect'),verseSelect=$('verseSelect');chapterSelect.disabled=true;verseSelect.disabled=true;$('browseVerse').disabled=true;try{const d=await loadBook(b);if(id!==pickerRequest)return;const chapters=[...new Set(Object.keys(d).map(k=>+k.split(':')[0]))].sort((a,b)=>a-b);chapterSelect.innerHTML=chapters.map(c=>`<option value="${c}">${c}장</option>`).join('');chapterSelect.value=String(chapters.includes(+chapter)?+chapter:chapters[0]);updateVersePicker(d);chapterSelect.disabled=false;verseSelect.disabled=false;$('browseVerse').disabled=false;}catch{$('pickerStatus').textContent='책 데이터를 불러오지 못했습니다. 다시 선택해주세요.';}}
function updateVersePicker(data){const c=+$('chapterSelect').value;$('verseSelect').innerHTML='<option value="all">장 전체</option>'+Object.keys(data).filter(k=>+k.split(':')[0]===c).map(k=>`<option value="${k.split(':')[1]}">${k.split(':')[1]}절</option>`).join('');$('pickerStatus').textContent='66권 전체 · 원문과 발음 제공';}
const pickerTimer=setInterval(()=>{if(!books.length)return;clearInterval(pickerTimer);$('bookSelect').innerHTML=['ot','nt'].map(t=>`<optgroup label="${t==='ot'?'구약 39권':'신약 27권'}">${books.filter(b=>b.testament===t).map(b=>`<option value="${b.code}">${b.name}</option>`).join('')}</optgroup>`).join('');$('bookSelect').onchange=()=>updatePicker($('bookSelect').value,1);$('chapterSelect').onchange=()=>{const b=books.find(b=>b.code===$('bookSelect').value);updateVersePicker(cache[b.code]);};$('browseVerse').onclick=()=>{const b=books.find(b=>b.code===$('bookSelect').value),c=$('chapterSelect').value,v=$('verseSelect').value;run(`${b.name} ${c}${v==='all'?'장':':'+v}`,'verse');};$('corpusScope').onchange=()=>{if(/[\u0590-\u05ff\u0370-\u03ff\u1f00-\u1fff]/.test($('query').value)||/^H\d+$/i.test($('query').value))run($('query').value);};updatePicker('Gen',1);},50);
