const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const nodes={};const element=()=>({value:'',dataset:{},classList:{toggle(){}},hidden:true,innerHTML:'',textContent:'',disabled:false});const context={document:{getElementById:id=>nodes[id]??=element(),querySelectorAll:()=>[],querySelector:()=>null},location:{href:'https://example.com/bible-original/'},URL,URLSearchParams,history:{replaceState(){}},navigator:{clipboard:{writeText:async()=>{}}},setInterval:()=>0,clearInterval(){},fetch:async url=>({ok:true,json:async()=>JSON.parse(fs.readFileSync(url,'utf8'))})};vm.createContext(context);for(const file of ['pronunciation.js','meanings.js','psalm-meanings.js','ai-config.js','ai-meaning.js','app.js','explorer.js'])vm.runInContext(fs.readFileSync(file,'utf8').replace(/\(async\(\)=>\{try\{const r=await fetch\('data\/books.json'\)[\s\S]*$/,''),context);const books=JSON.parse(fs.readFileSync('data/books.json','utf8'));vm.runInContext('books='+JSON.stringify(books),context);nodes.corpusScope=element();nodes.corpusScope.value='all';
(async()=>{for(const b of books){const data=JSON.parse(fs.readFileSync(`data/${b.code}.json`));for(const name of [b.name,b.short,b.code]){const p=context.parsePassage(`${name} 1:1`);assert.equal(p.book.code,b.code);assert.equal(p.verse,1);}const last=Object.keys(data).at(-1);await context.run(`${b.name} ${last}`,'verse');assert.ok(nodes.results.innerHTML.includes(data[last].text.slice(0,1)),b.name);assert.ok(nodes.results.innerHTML.includes('원문 발음'));}
for(const q of ['창세기 1장','창세기 1','창세기','요한복음 3:16-18','요 3장 16절','1John 1:1'])assert.ok(context.parsePassage(q),q);
await context.run('요한복음 3:16-18');assert.equal((nodes.results.innerHTML.match(/class="chapter-verse"/g)||[]).length,3);assert.ok(nodes.results.innerHTML.includes('요한복음 3:18'));
await context.run('창세기 1장');assert.equal((nodes.results.innerHTML.match(/class="chapter-verse"/g)||[]).length,31);
await context.run('H8081');assert.ok(nodes.results.innerHTML.includes('출애굽기'));assert.ok(nodes.results.innerHTML.includes('성경 전체 용례')===false);assert.ok(nodes.results.innerHTML.includes('개 구절'));
await context.run('H8081');assert.equal((nodes.results.innerHTML.match(/30:25<\/span>[^]*?<\/button>/)[0].match(/<mark>/g)||[]).length,2,'Strong hits highlighted');assert.ok(nodes.results.innerHTML.includes('class="hit-book"'));assert.ok(nodes.results.innerHTML.includes('data-book="Exod"'));nodes.corpusScope.value='nt';await context.run('λογος');assert.ok(nodes.results.innerHTML.includes('<mark>λόγος</mark>'),'Greek hit highlighted');assert.equal(vm.runInContext('highlightHit',context)({text:'Ἐν ἀρχῇ ἦν ὁ λόγος'},null,vm.runInContext('stripOriginal',context)('ΑΡΧΗ')),'Ἐν <mark>ἀρχῇ</mark> ἦν ὁ λόγος');assert.ok(nodes.results.innerHTML.includes('요한복음'));assert.ok(nodes.results.innerHTML.includes('1:1'));
context.stripOriginal=vm.runInContext('stripOriginal',context);const n=context.stripOriginal('λόγος');assert.equal(n,context.stripOriginal('λογοσ'));assert.equal(context.stripOriginal('שֶׁמֶן'),context.stripOriginal('שמן'));
await context.run('창세기 999장');assert.ok(nodes.results.innerHTML.includes('해당 장·절이 없습니다'));
await context.run('시편 57:7');assert.ok(nodes.results.innerHTML.includes('내 마음은 굳게 서 있습니다'));assert.ok(nodes.results.innerHTML.includes('WLC: 57:8'));assert.ok(nodes.results.innerHTML.includes('니팔 분사'));
console.log('PASS: all 66 books, book names/abbreviations/codes, last verses, chapter/range reading, Hebrew Strong concordance, Greek concordance, diacritics, invalid chapters');})();
