const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const nodes={};const element=()=>({value:'',dataset:{},classList:{toggle(){}},hidden:true,innerHTML:'',textContent:'',disabled:false});const context={document:{getElementById:id=>nodes[id]??=element(),querySelectorAll:()=>[],querySelector:()=>null},location:{href:'https://example.com/bible-original/'},URL,URLSearchParams,history:{replaceState(){}},navigator:{clipboard:{writeText:async()=>{}}},setInterval:()=>0,clearInterval(){},fetch:async url=>({ok:true,json:async()=>JSON.parse(fs.readFileSync(url,'utf8'))})};vm.createContext(context);for(const file of ['pronunciation.js','meanings.js','psalm-meanings.js','ai-config.js','ai-meaning.js','morph.js','study.js','app.js','explorer.js'])vm.runInContext(fs.readFileSync(file,'utf8').replace(/\(async\(\)=>\{try\{const r=await fetch\('data\/books.json'\)[\s\S]*$/,''),context);const books=JSON.parse(fs.readFileSync('data/books.json','utf8'));vm.runInContext('books='+JSON.stringify(books),context);
(async()=>{for(const b of books){const data=JSON.parse(fs.readFileSync(`data/${b.code}.json`));for(const name of [b.name,b.short,b.code]){const p=context.parsePassage(`${name} 1:1`);assert.equal(p.book.code,b.code);assert.equal(p.verse,1);}const last=Object.keys(data).at(-1);await context.run(`${b.name} ${last}`,'verse');assert.ok(nodes.results.innerHTML.includes(data[last].text.slice(0,1)),b.name);assert.ok(nodes.results.innerHTML.includes('원문 발음'));}
for(const q of ['창세기 1장','창세기 1','창세기','요한복음 3:16-18','요 3장 16절','1John 1:1'])assert.ok(context.parsePassage(q),q);
await context.run('요한복음 3:16-18');assert.equal((nodes.results.innerHTML.match(/class="chapter-verse"/g)||[]).length,3);assert.ok(nodes.results.innerHTML.includes('요한복음 3:18'));
await context.run('창세기 1장');assert.equal((nodes.results.innerHTML.match(/class="chapter-verse"/g)||[]).length,31);
await context.run('H8081');assert.ok(nodes.results.innerHTML.includes('출애굽기'));assert.ok(nodes.results.innerHTML.includes('성경 전체 용례')===false);assert.ok(nodes.results.innerHTML.includes('개 구절'));
await context.run('H8081');assert.equal((nodes.results.innerHTML.match(/30:25<\/span>[^]*?<\/button>/)[0].match(/<mark>/g)||[]).length,2,'Strong hits highlighted');assert.ok(nodes.results.innerHTML.includes('class="hit-book"'));assert.ok(nodes.results.innerHTML.includes('data-scope="ot"'),'scope toggle in corpus results');assert.ok(nodes.results.innerHTML.includes('data-book="Exod"'));assert.ok(nodes.results.innerHTML.includes('+20권 더보기'));assert.equal((nodes.results.innerHTML.match(/dist-chip extra/g)||[]).length,20);assert.deepEqual([...nodes.results.innerHTML.matchAll(/data-book="(\w+)"/g)].slice(0,3).map(m=>m[1]),['Lev','Num','Exod'],'chips sorted by count');vm.runInContext("corpusScope='nt'",context);await context.run('λογος');assert.ok(nodes.results.innerHTML.includes('<mark>λόγος</mark>'),'Greek hit highlighted');assert.equal(vm.runInContext('highlightHit',context)({text:'Ἐν ἀρχῇ ἦν ὁ λόγος'},null,vm.runInContext('stripOriginal',context)('ΑΡΧΗ')),'Ἐν <mark>ἀρχῇ</mark> ἦν ὁ λόγος');assert.ok(nodes.results.innerHTML.includes('요한복음'));assert.ok(nodes.results.innerHTML.includes('1:1'));
context.stripOriginal=vm.runInContext('stripOriginal',context);const n=context.stripOriginal('λόγος');assert.equal(n,context.stripOriginal('λογοσ'));assert.equal(context.stripOriginal('שֶׁמֶן'),context.stripOriginal('שמן'));
await context.run('창세기 999장');assert.ok(nodes.results.innerHTML.includes('해당 장·절이 없습니다'));
await context.run('시편 57:7');assert.ok(nodes.studyReading.innerHTML.includes('내 마음은 굳게 서 있습니다'));assert.ok(nodes.results.innerHTML.includes('WLC: 57:8'));assert.ok(nodes['panel-terms'].innerHTML.includes('니팔 분사'));await context.run('잠언 16:9');assert.ok(nodes.results.innerHTML.includes('class="iw-p"'),'interlinear pronunciation');assert.equal(nodes.gloss0.textContent,'마음','gloss under first word');assert.equal(nodes['tab-terms'].textContent,'핵심 단어 5');vm.runInContext('showWordDetail(0)',context);assert.ok(nodes.wordDetail.innerHTML.includes('data-query="H3820"'),'word detail links Strong concordance');assert.ok(nodes.wordDetail.innerHTML.includes('감정뿐 아니라'));await vm.runInContext('applyBasicGlosses()',context);assert.equal(nodes.gloss0.textContent,'마음','key-term meaning wins over basic gloss');{const st=vm.runInContext('studyState',context),j=st.matches.findIndex(m=>m.ti<0);assert.ok(j>=0);assert.equal(nodes['gloss'+j].textContent,st.basic[j]);assert.ok(st.basic.every(Boolean),'basic gloss for every Hebrew word');vm.runInContext(`showWordDetail(${j})`,context);}assert.ok(nodes.wordDetail.innerHTML.includes('기본 뜻'));await context.run('요한복음 3:16');const john=vm.runInContext('studyState',context);assert.ok(john.matches.some(m=>m.label),'Greek words get glosses');await vm.runInContext('applyBasicGlosses()',context);assert.ok(john.tokens.every((_,i)=>nodes['gloss'+i].textContent),'every Greek word has a gloss');vm.runInContext('showWordDetail(5)',context);assert.ok(nodes.wordDetail.innerHTML.includes('표제어 ὁ'));vm.runInContext('showWordDetail(2)',context);assert.ok(nodes.wordDetail.innerHTML.includes('<b>동사</b> 부정과거(아오리스트) · 능동태 · 직설법 · 3인칭 · 단수'),'Greek parsing in Korean');assert.ok(nodes.wordDetail.innerHTML.includes('MorphGNT 형태 코드 V-3AAI-S--'));
console.log('PASS: all 66 books, book names/abbreviations/codes, last verses, chapter/range reading, Hebrew Strong concordance, Greek concordance, diacritics, invalid chapters');})();
{const he=vm.runInContext('morphHebrew',context),gr=vm.runInContext('morphGreek',context);
const w=he('HC/Vqw3ms');assert.equal(w.segs[0].pos,'접속사');assert.deepEqual([...w.segs[1].feats],['칼(Qal)','연속 미완료(와이크톨)','3인칭','남성','단수']);
assert.deepEqual([...he('HNcmsc').segs[0].feats],['남성','단수','연계형']);assert.deepEqual([...he('HVqrmsa').segs[0].feats],['칼(Qal)','능동 분사','남성','단수','절대형']);
assert.equal(he('HTd/Ncmpa').segs[0].pos,'정관사');assert.equal(he('HR/Sp3ms').segs[1].pos,'대명사 접미어');assert.equal(he('AVhp3ms').lang,'아람어');assert.equal(he('AVhp3ms').segs[0].feats[0],'하펠(Haphel)');
const seen=new Set();for(const b of books.filter(b=>b.testament==='ot'))for(const v of Object.values(JSON.parse(fs.readFileSync(`data/${b.code}.json`,'utf8'))))for(const x of v.words||[])seen.add(x.m);
for(const m of seen){const r=he(m);assert.ok(r,'decodes '+m);m.slice(1).split('/').forEach((c,i)=>{const chars=[...c.slice(1)].filter(ch=>ch!=='x').length;const merged=('TSPR'.includes(c[0])&&c.length>1)||(c[0]==='A'&&c[1]==='a')||(c[0]==='N'&&c[1]==='c');assert.equal(r.segs[i].feats.length,chars-(merged?1:0),'every feature decoded in '+m);});}
for(const c of JSON.parse(fs.readFileSync('data/morph-gr.json','utf8'))){const r=gr(c);assert.ok(r,'decodes '+c);assert.equal(r.segs[0].feats.length,[...c.slice(2)].filter(ch=>ch!=='-').length,'every feature decoded in '+c);}
console.log(`PASS: morphology decoding (${seen.size} Hebrew codes, Greek table)`);}

